const LIMIT = 10;
SORT_BY_DURATION = 'duration';
SORT_BY_QUEUED_DURATION = 'queuedDuration';

exports.LIMIT = LIMIT;
exports.SORT_BY_DURATION = SORT_BY_DURATION;
exports.SORT_BY_QUEUED_DURATION = SORT_BY_QUEUED_DURATION;
